apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        tags.datadoghq.com/env: "prod"
        tags.datadoghq.com/service: {{ .Values.name }}
        tags.datadoghq.com/version: "003"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/python-lib.version: v1.7.2
        ad.datadoghq.com/{{ .Values.name }}.logs: {{ .Values.datadogLogsTag | quote }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.repo }}/{{ .Values.image }}:{{ .Values.imageTag }}
        {{- if .Values.command }}
        command:
        {{- range .Values.command }}
        - {{. | quote}}
        {{- end }}
        {{- end }}
        {{- if .Values.args }}
        args:
        {{- range .Values.args }}
        - {{. | quote}}
        {{- end }}
        {{- end }}
        env:
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_TRACE_SAMPLE_RATE
          value: "1"
        - name: FL_BACKEND_DATABASE_URL
          value: "postgresql+asyncpg://postgres:postgres@age:5432"
        - name: FL_BACKEND_SELF_URL
          value: "https://learning.aptakhin.name"
        - name: FL_SENDER_EMAIL
          value: "noreply@aptakhin.name"
        - name: FL_JWT_A14N_TOKEN
          value: {{ .Values.jwtA14nToken }}
        - name: FL_SENDGRID_TOKEN
          value: {{ .Values.sendgridToken }}
        ports:
        - containerPort: {{ .Values.exposePort }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
