apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.repo }}/{{ .Values.image }}:{{ .Values.imageTag }}
        {{- if .Values.command }}
        command:
        {{- range .Values.command }}
        - {{. | quote}}
        {{- end }}
        {{- end }}
        {{- if .Values.args }}
        args:
        {{- range .Values.args }}
        - {{. | quote}}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.exposePort }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
