apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - port: {{ .Values.exposePort }}
    protocol: TCP
  selector:
    app: {{ .Values.name }}
