"""Init

Revision ID: 0dd6b3a9cf61
Revises:
Create Date: 2023-01-05 21:53:30.783286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0dd6b3a9cf61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('create extension "uuid-ossp"')

    op.create_table('accounts',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='organizations_slug_unique_idx')
    )
    op.create_table('account_authentification_types',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('account_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'key', name='account_authentifications_type_key_unique_idx')
    )
    op.create_table('account_authententifications',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_authentification_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_authententifications')
    op.drop_table('account_authentification_types')
    op.drop_table('organizations')
    op.drop_table('accounts')
    # ### end Alembic commands ###
