"""Contraints

Revision ID: 27b1f4a28764
Revises: 6612370ae0b5
Create Date: 2023-01-08 15:04:20.689654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b1f4a28764'
down_revision = '6612370ae0b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'account_a14n_signature_provider_type_value_idx',
        'account_a14n_signature',
        ['account_a14n_provider_type', 'value'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'account_a14n_signature_provider_type_value_idx',
        'account_a14n_signature',
        type_='unique',
    )
    # ### end Alembic commands ###
