name: Rollout
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

env:
  IMAGE_REGISTRY: registry.digitalocean.com/frlr

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2.3.0
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save free-learning-k8s

    - name: Log in to DO Container Registry
      run: doctl registry login --expiry-seconds 600

    # - name: Echo
    #   env:
    #     IMAGE_NAME: backend
    #   run: |
    #     echo "::set-output name=image::$IMAGE_REGISTRY_BASE/$IMAGE_REGISTRY/$IMAGE_NAME:${{  github.run_id }}"

    - name: Build and push
      uses: docker/build-push-action@v3
      env:
        IMAGE_NAME: backend
      with:
        context: backend
        push: true
        tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}
