apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learning-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: backend
      port:
        number: 8000
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port:
              number: 8000
      - pathType: Prefix
        path: "/api(/|$)(.*)"
        backend:
          service:
            name: backend
            port:
              number: 8000
